//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockChat.Core.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RockLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RockLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RockChat.Core.i18n.RockLocalization", typeof(RockLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created a snippet.
        /// </summary>
        public static string Created_snippet {
            get {
                return ResourceManager.GetString("Created_snippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has joined the channel.
        /// </summary>
        public static string Has_joined_the_channel {
            get {
                return ResourceManager.GetString("Has_joined_the_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has joined the conversation.
        /// </summary>
        public static string Has_joined_the_conversation {
            get {
                return ResourceManager.GetString("Has_joined_the_conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has left the channel.
        /// </summary>
        public static string Has_left_the_channel {
            get {
                return ResourceManager.GetString("Has_left_the_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message pinned.
        /// </summary>
        public static string Message_pinned {
            get {
                return ResourceManager.GetString("Message_pinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message removed.
        /// </summary>
        public static string Message_removed {
            get {
                return ResourceManager.GetString("Message_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room announcement changed to:  {0} by {1}.
        /// </summary>
        public static string Room_changed_announcement {
            get {
                return ResourceManager.GetString("Room_changed_announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room description changed to: {0} by {1}.
        /// </summary>
        public static string Room_changed_description {
            get {
                return ResourceManager.GetString("Room_changed_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room type changed to: {0} by {1}.
        /// </summary>
        public static string Room_changed_privacy {
            get {
                return ResourceManager.GetString("Room_changed_privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room topic changed to: {0} by {1}.
        /// </summary>
        public static string Room_changed_topic {
            get {
                return ResourceManager.GetString("Room_changed_topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room name changed to: {0} by {1}.
        /// </summary>
        public static string Room_name_changed {
            get {
                return ResourceManager.GetString("Room_name_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call started by {0}.
        /// </summary>
        public static string Started_call {
            get {
                return ResourceManager.GetString("Started_call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} added by {1}.
        /// </summary>
        public static string User_added_by {
            get {
                return ResourceManager.GetString("User_added_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} muted by {1}.
        /// </summary>
        public static string User_muted_by {
            get {
                return ResourceManager.GetString("User_muted_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} removed by {1}.
        /// </summary>
        public static string User_removed_by {
            get {
                return ResourceManager.GetString("User_removed_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was set {1} by {2}.
        /// </summary>
        public static string User_role_add {
            get {
                return ResourceManager.GetString("User_role_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is no longer {1} by {2}.
        /// </summary>
        public static string User_role_remove {
            get {
                return ResourceManager.GetString("User_role_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} unmuted by {1}.
        /// </summary>
        public static string User_unmuted_by {
            get {
                return ResourceManager.GetString("User_unmuted_by", resourceCulture);
            }
        }
    }
}
